# Generated by Django 3.2.4 on 2021-06-23 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_Id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_Name', models.CharField(max_length=40)),
                ('emp_Department', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('emp_Sal_Id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_Salary', models.IntegerField()),
                ('emp_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
    ]
