# Generated by Django 3.2.4 on 2021-06-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_emp_id_employeesalary_emp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCategory',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
